apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::167771397877:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-K0QQ1LEWO2ES
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::167771397877:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-16T08:23:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3440"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c7f4a658-7507-441a-a577-da7c7927c47b
